// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import {
  availableLocationAttributesPickUpPickUpDetails,
  availableLocationAttributesPickUpPickUpDetailsRequest,
  availableLocationAttributesPickUpPickUpDetailsResponse,
} from './available-location-attributes-pick-up-pick-up-details';

/**
 * The shape of the model inside the application code - what the users use
 */
export const availableLocationAttributesTransportationPickUpSchedulePickUp: any = z.lazy(() => {
  return z.object({
    dayOfWeek: z.string().min(1).max(1),
    pickUpDetails: availableLocationAttributesPickUpPickUpDetails,
  });
});

/**
 * 
 * @typedef  {AvailableLocationAttributesTransportationPickUpSchedulePickUp} availableLocationAttributesTransportationPickUpSchedulePickUp   
 * @property {string} - Day of the week for scheduled pickup. Valid values are:
- 1 - Sunday
- 2 - Monday
- 3 - Tuesday
- 4 - Wednesday
- 5 - Thursday
- 6 - Friday
- 7 - Saturday.

 * @property {AvailableLocationAttributesPickUpPickUpDetails} - Container to hold information regarding pickup time and pickup availability indicator.
 */
export type AvailableLocationAttributesTransportationPickUpSchedulePickUp = z.infer<
  typeof availableLocationAttributesTransportationPickUpSchedulePickUp
>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const availableLocationAttributesTransportationPickUpSchedulePickUpResponse: any = z.lazy(() => {
  return z
    .object({
      DayOfWeek: z.string().min(1).max(1),
      PickUpDetails: availableLocationAttributesPickUpPickUpDetailsResponse,
    })
    .transform((data) => ({
      dayOfWeek: data['DayOfWeek'],
      pickUpDetails: data['PickUpDetails'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const availableLocationAttributesTransportationPickUpSchedulePickUpRequest: any = z.lazy(() => {
  return z
    .object({
      dayOfWeek: z.string().nullish(),
      pickUpDetails: availableLocationAttributesPickUpPickUpDetailsRequest.nullish(),
    })
    .transform((data) => ({
      DayOfWeek: data['dayOfWeek'],
      PickUpDetails: data['pickUpDetails'],
    }));
});
