// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

/**
 * The shape of the model inside the application code - what the users use
 */
export const availableLocationAttributesPickUpPickUpDetails = z.object({
  pickUpTime: z.string().min(4).max(4).optional(),
  noPickUpIndicator: z.string(),
});

/**
 * Container to hold information regarding pickup time and pickup availability indicator.
 * @typedef  {AvailableLocationAttributesPickUpPickUpDetails} availableLocationAttributesPickUpPickUpDetails - Container to hold information regarding pickup time and pickup availability indicator. - Container to hold information regarding pickup time and pickup availability indicator.
 * @property {string} - Time of pickup in military format (HHMM) e.g. 0930, 1700, 1845 etc. with exception for midnight. For midnight the time will be returned as 0.
 * @property {string} - Indicates whether or not there is a pickup time for the specified day of the week. Valid values:
- True-there is a pickup time
- False-there is not a pickup time.

 */
export type AvailableLocationAttributesPickUpPickUpDetails = z.infer<
  typeof availableLocationAttributesPickUpPickUpDetails
>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const availableLocationAttributesPickUpPickUpDetailsResponse = z
  .object({
    PickUpTime: z.string().min(4).max(4).optional(),
    NoPickUpIndicator: z.string(),
  })
  .transform((data) => ({
    pickUpTime: data['PickUpTime'],
    noPickUpIndicator: data['NoPickUpIndicator'],
  }));

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const availableLocationAttributesPickUpPickUpDetailsRequest = z
  .object({ pickUpTime: z.string().nullish(), noPickUpIndicator: z.string().nullish() })
  .transform((data) => ({
    PickUpTime: data['pickUpTime'],
    NoPickUpIndicator: data['noPickUpIndicator'],
  }));
