// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

/**
 * The shape of the model inside the application code - what the users use
 */
export const includeCriteriaMerchantAccountNumberList: any = z.lazy(() => {
  return z.object({
    merchantAccountNumber: z.array(z.string()),
  });
});

/**
 * This contains the list of Merchant Account numbers to be used for finding private network access points.
 * @typedef  {IncludeCriteriaMerchantAccountNumberList} includeCriteriaMerchantAccountNumberList - This contains the list of Merchant Account numbers to be used for finding private network access points. - This contains the list of Merchant Account numbers to be used for finding private network access points.
 * @property {string[]} - Account number to be used for a private network access point search where a UPS access point candidate list is obtained in search by address or geocode search.
 */
export type IncludeCriteriaMerchantAccountNumberList = z.infer<typeof includeCriteriaMerchantAccountNumberList>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const includeCriteriaMerchantAccountNumberListResponse: any = z.lazy(() => {
  return z
    .object({
      MerchantAccountNumber: z.array(z.string()),
    })
    .transform((data) => ({
      merchantAccountNumber: data['MerchantAccountNumber'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const includeCriteriaMerchantAccountNumberListRequest: any = z.lazy(() => {
  return z.object({ merchantAccountNumber: z.array(z.string()).nullish() }).transform((data) => ({
    MerchantAccountNumber: data['merchantAccountNumber'],
  }));
});
