// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import { BaseService } from '../base-service';
import { ContentType, HttpResponse } from '../../http';
import { RequestConfig } from '../../http/types';
import { Request } from '../../http/transport/request';
import { LocatorRequestWrapper, locatorRequestWrapperRequest } from '../common/locator-request-wrapper';
import { LocatorResponseWrapper, locatorResponseWrapperResponse } from '../common/locator-response-wrapper';
import { LocatorParams } from './request-params';

export class LocationsService extends BaseService {
  /**
 * The Locator API allows you to find UPS locations - such as drop-off points, retail locations, and UPS access points (third-party retail locations that offer UPS package drop-off, or delivery services). The API provides capabilities to search by location, services offered, program types, and related criteria. You can also retrieve hours of operation, location details, and additional UPS services offered at specific locations.
 * @param {string} version - Version of API

Valid values:
- v2

 * @param {string} reqOption - Indicates the type of request.
Valid values:
1-Locations (Drop Locations and Will call locations)
8-All available Additional Services
16-All available Program Types
24-All available Additional Services and Program types
32-All available Retail Locations
40-All available Retail Locations and Additional Services 
48-All available Retail Locations and Program Types 
56-All available Retail Locations, Additional Services and Program Types 
64-Search for UPS Access Point Locations.  
 * @param {string} [locale] - Locale of request
 * @param {string} [transId] - An identifier unique to the request. Length 32
 * @param {string} [transactionSrc] - An identifier of the client/source application that is making the request.Length 512
 * @returns {Promise<HttpResponse<LocatorResponseWrapper>>} successful operation
 */
  async locator(
    version: string,
    reqOption: string,
    body: LocatorRequestWrapper,
    params?: LocatorParams,
    requestConfig?: RequestConfig,
  ): Promise<HttpResponse<LocatorResponseWrapper>> {
    const request = new Request({
      method: 'POST',
      body,
      path: '/locations/{version}/search/availabilities/{reqOption}',
      config: this.config,
      responseSchema: locatorResponseWrapperResponse,
      requestSchema: locatorRequestWrapperRequest,
      requestContentType: ContentType.Json,
      responseContentType: ContentType.Json,
      requestConfig,
    });
    request.addPathParam('version', version);
    request.addPathParam('reqOption', reqOption);
    request.addQueryParam('Locale', params?.locale);
    request.addHeaderParam('transId', params?.transId);
    request.addHeaderParam('transactionSrc', params?.transactionSrc);
    request.addHeaderParam('Content-Type', 'application/json');
    return this.client.call(request);
  }
}
