// This file was generated by liblab | https://liblab.com/

import { Environment } from './http/environment';
import { SdkConfig } from './http/types';
import { _Version_Service } from './services/_version_';
import { _DeprecatedVersion_Service } from './services/_deprecated-version_';

export class UpsLocator {
  public readonly _version_: _Version_Service;

  public readonly _deprecatedVersion_: _DeprecatedVersion_Service;

  constructor(public config: SdkConfig) {
    const baseUrl = config.environment || config.baseUrl || Environment.DEFAULT;
    this.config = {
      ...config,
      baseUrl,
    };
    this._version_ = new _Version_Service(this.config);

    this._deprecatedVersion_ = new _DeprecatedVersion_Service(this.config);
  }

  set baseUrl(baseUrl: string) {
    this._version_.baseUrl = baseUrl;
    this._deprecatedVersion_.baseUrl = baseUrl;
  }

  set environment(environment: Environment) {
    this._version_.baseUrl = environment;
    this._deprecatedVersion_.baseUrl = environment;
  }

  set username(username: string) {
    this._version_.username = username;
    this._deprecatedVersion_.username = username;
  }

  set password(password: string) {
    this._version_.password = password;
    this._deprecatedVersion_.password = password;
  }
}

// c029837e0e474b76bc487506e8799df5e3335891efe4fb02bda7a1441840310c
