// This file was generated by liblab | https://liblab.com/

import { Environment } from './http/environment';
import { SdkConfig } from './http/types';
import { LocationsService } from './services/locations';
import { DeprecatedService } from './services/deprecated';

export class UpsLocator {
  public readonly locations: LocationsService;

  public readonly deprecated: DeprecatedService;

  constructor(public config: SdkConfig) {
    const baseUrl = config.environment || config.baseUrl || Environment.DEFAULT;
    this.config = {
      ...config,
      baseUrl,
    };
    this.locations = new LocationsService(this.config);

    this.deprecated = new DeprecatedService(this.config);
  }

  set baseUrl(baseUrl: string) {
    this.locations.baseUrl = baseUrl;
    this.deprecated.baseUrl = baseUrl;
  }

  set environment(environment: Environment) {
    this.locations.baseUrl = environment;
    this.deprecated.baseUrl = environment;
  }

  set timeout(timeout: number) {
    this.locations.timeout = timeout;
    this.deprecated.timeout = timeout;
  }

  set username(username: string) {
    this.locations.username = username;
    this.deprecated.username = username;
  }

  set password(password: string) {
    this.locations.password = password;
    this.deprecated.password = password;
  }
}

// c029837e0e474b76bc487506e8799df5e3335891efe4fb02bda7a1441840310c
